### ISSUE TITLE
CUDA errors regarding illegal memory addresses

### ISSUE THREAD

**Issue by Ratolon** [ma-gilles/recovar#10]
Dear developers,

We are trying to intergrate recovar into Scipion. I've got two servers. 

Server A
- GTX 1080Ti (11G), RTX 2080Ti (11G) and 4500Ada (24G).
- Ubuntu 24.04LTS, gcc-12, miniforge3

Server B
- Tesla T4 (16G)
- Ubuntu 22.04LTS, gcc-12, miniforge3

We tried to install recovar+cryodrgn as per the instructions in the main GitHub page, and then running "recovar run_test_dataset". On server A all tests pass. On server B, however, none of them pass.

In both cases, there is +500GB free on the root disk, and no one is using the GPUs. I'm attaching the error from server B. It's full of messages about illegal memory accesses after XLA compilation of some CUAD kernels. Any idea on why the vanilla installation fails on B but not on A?

Thanks in advance,
M. Iceta, BioComputing Unit CNB-CSIC

[recovar_error.txt](https://github.com/user-attachments/files/19409677/recovar_error.txt)

**Comment by Ratolon** [comment]
For further details: both servers have 512GB of RAM. The one that works is a dual Xeon E5-2699v4 and the one that does not is a dual Xeon E5-2630v4.

**Comment by ma-gilles** [comment]
Hi Mikel,

Thank you for taking the time to integrate it into Scipion, that's fantastic!

That is odd, since it appears JAX is finding the GPU, and the data generation works, but everything else fails. Can you check if there is a log file named run.log in /tmp//test_dataset/pipeline_output/? It may give me some idea of what is happening.

Can you also send me those messages "about illegal memory accesses after XLA compilation of some CUDA kernels"?

My first guess is that something is not compatible between the CUDA drivers and JAX, but I am not sure, I have not seen this before. Here's the corresponding section on the JAX [webpage](https://docs.jax.dev/en/latest/installation.html#nvidia-gpu):

> NVIDIA GPU
> JAX supports NVIDIA GPUs that have SM version 5.2 (Maxwell) or newer. Note that Kepler-series GPUs are no longer supported by JAX since NVIDIA has dropped support for Kepler GPUs in its software.
> 
> You must first install the NVIDIA driver. You’re recommended to install the newest driver available from NVIDIA, but the driver version must be >= 525.60.13 for CUDA 12 on Linux.
> 
> If you need to use a newer CUDA toolkit with an older driver, for example on a cluster where you cannot update the NVIDIA driver easily, you may be able to use the [CUDA forward compatibility packages](https://docs.nvidia.com/deploy/cuda-compatibility/) that NVIDIA provides for this purpose.


Best,
Marc

**Comment by Ratolon** [comment]
Dear Marc,

Thanks for your fast response! Both machines are running nvidia-driver-570, and all GPU architectures are supported in Jax. I've just seen that the txt I'm providing excludes all of the stderr output... Sorry. 

 /tmp//test_dataset/pipeline_output/run.log does not have these errors either. The attached one has the errors.

[errorlog.txt](https://github.com/user-attachments/files/19409946/errorlog.txt)

Wbw,
Mikel.

**Comment by ma-gilles** [comment]
Thanks! That does not look good indeed! I don't know what it it could be, but to rule out some problems, can you:

1. check the jax/jaxlib version:

python -c "import jax; print(jax.__version__); import jaxlib; print(jaxlib.__version__)"

2. Make sure that no other processes are running on the gpu at the same time (you can do it by running `nvidia-smi`),
then run the pipeline alone part, that is, run this command:

recovar pipeline /tmp//test_dataset/particles.64.mrcs --poses /tmp//test_dataset/poses.pkl --ctf /tmp//test_dataset/ctf.pkl --correct-contrast -o /tmp//test_dataset/pipeline_output --mask=from_halfmaps --lazy --ignore-zero-frequency

**Comment by ma-gilles** [comment]
Also, can you check if you can allocate a 5 gb array on the GPU without errors. You can do this by:

`python -c "import jax.numpy as jnp, jax; a=jax.device_put(jnp.zeros((int((5*1024**3)//4,), dtype=jnp.float32)); print(f'Allocated {a.size * a.itemsize / 1e9:.2f} GB on {a.device()}')"
`

**Comment by Ratolon** [comment]
Hi,

I can allocate 5, 10 and 15GB using Jax through the python console, reaching the max of this 16GB GPU. Both Jax and Jaxlib report 0.5.0 as their version.

I've run the pipeline alone and still get the errors. Tried to add CUDA_VISIBLE_DEVICES=0 to use a single GPU and get less information on screen. When using a single GPU it now crashes at a later time, after doing some of the calculations (see attached txt).

[err_singlegpu.txt](https://github.com/user-attachments/files/19410509/err_singlegpu.txt)

After that, it's the same cuda_executor.cc error with the leaking and illegal address message over and over again. Any guess based on that?

Wbw..M

**Comment by ma-gilles** [comment]
Thanks, that narrows it down but unfortunately, I still don't understand what could be causing this. This sounds like an internal JAX bug to me. Occasionally, they are fixed by updating the JAX version (e.g., they seemed to have fixed a similar problem recently [here](https://github.com/jax-ml/jax/issues/25002)).

Can you try to use the latest jax version and see if that helps?
E.g., make a new environment like this:

conda create --name recovar python=3.11 -y
conda activate recovar
pip install -f https://download.pytorch.org/whl/torch_stable.html torch==2.3.1+cpu **"jax[cuda12]"==0.5.3**  recovar

and try again. If it still doesn't work, can you set  JAX_TRACEBACK_FILTERING=off and try again to see if it gives us a better idea about what's happening?

**Comment by Ratolon** [comment]
Hi again!

Same problem... traceback does not give any additional information sadly. For the moment I'll be moving the work to the server in which it's working, and after having an initial integration with Scipion we'll be coming back to this.  Sadly we have an internal deadline for a student to get recovar in Scipion so we have to move away from the issue for now. 

I guess we can close this now and I'll ping you when we get back to it? In the meantime, if I get to solve the issue I'll send you the resolution.

Thank you very much for your continued attention!

Wbw..M

**Comment by ma-gilles** [comment]
Hi Mikel,

Okay, sorry I couldn't be more helpful. I have no great ideas at this point, but I'll ask around to see if I can find an explanation. Let's leave it open so I remember it's a problem!

Thanks!
Marc

**Comment by Ratolon** [comment]
Dear Marc,

Don't worry, these kind of problems are very hard to debug! Thank you very much for your responses.

I found the problem, let me explain. Our machine has a CUDA 12.3 toolkit installed in /usr/local/cuda. My user did have its PATH and LD_LIBRARY_PATH variables set to use nvcc there. So, when launching recovar, one of the steps involver using nvcc for the XLA compilation... And it was using the system-wide CUDA instead of the one in the conda environment!

This was mixing toolkits and compilers, resulting in wrong ptx code being generated and the subsequent memory management errors.

After removing the system CUDA from PATH and LD_LIBRARY_PATH,  recovar works like a charm. So the problem is having a mixture in the CUDA toolkits, specifically nvcc.

Wbw..M

**Comment by ma-gilles** [comment]
Hi Mikel,

Ah ok! Glad it's fixed and thanks for letting me know, that's really good to know!

Best,
Marc
